### ISSUE TITLE
Math methods with type double

### ISSUE THREAD

**Issue by jacokok** [Handlebars-Net/Handlebars.Net.Helpers#34]
Difficulty using Math methods with type double.
Methods like Math.Divide should also work with int and other number types.

```csharp
public class Test
{
    public int Value1 { get; set; }
    public int Value2 { get; set; }
    public double Value3 { get; set; } // This works
}

var handlebars = Handlebars.Create();
HandlebarsHelpers.Register(handlebars);

Test test = new();
test.Value1 = 10;
test.Value2 = 21;

var template = handlebars.Compile("{{Math.Divide Value1 Value2}}");
string result = template(test);
```
Using this with NewtonsoftJson extension makes it difficult.
I am doing something wrong or what do you recommend?

**Comment by jacokok** [comment]
Example {{Math.Divide 4 5}} does not work for me either.
When I use class with double types then only will it work.

Getting 

Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at HandlebarsDotNet.Helpers.HandlebarsHelpers.InvokeMethod(Nullable`1 model, Boolean methodIsOnlyUsedInContextOfABlockHelper, IHandlebars context, String helperName, MethodInfo methodInfo, Arguments arguments, Object instance)
   at HandlebarsDotNet.Helpers.HandlebarsHelpers.<>c__DisplayClass6_0.<RegisterValueHelper>b__0(Context context, Arguments arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method1(Closure , EncodedTextWriter& , BindingContext )
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
   at HandlebarsTest.Program.Main(String[] args) in C:\projects\temp\HandlebarsTest\Program.cs:line 24

**Comment by StefH** [comment]
Hello @jacokok.
Thank you for finding this issue. I'll fix it and a new NuGet will be released shortly.
